name: "Puppet"
description: "Turn dashboards into nice pictures"
version: "2.7.0"
slug: "puppet"
homeassistant_api: true
arch:
  - aarch64
  - amd64
ports:
  10000/tcp: 10000
webui: "http://[HOST]:[PORT:10000]/"
options:
  access_token: ""
  keep_browser_open: false
  home_assistant_url: "http://homeassistant:8123"
schema:
  access_token: password
  keep_browser_open: bool
  home_assistant_url: str
